name: "moon - CI booster"
description: "Posts per-task failure comments with stderr on pull requests and a summary to the job step."
inputs:
  access-token:
    description: "GitHub access token to post comments."
    required: true
  workspace-root:
    description: "Root of the moon workspace. Defaults to working directory."
    default: ""

outputs:
  comment-created:
    description: "Whether or not a comment was created/updated on the pull request."
  has-failures:
    description: "'true' if any failing tasks were found."
  report:
    description: "The generated failure summary markdown."
runs:
  using: node20
  main: dist/index.js
branding:
  icon: "alert-triangle"
  color: "red"
